### ISSUE TITLE
Write blogpost on 'usage of the DataHub to do KPIs stuff'

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/datahub-metrics#1]
The purpose of this blog post is to showcase how we're using datahub to improve our own internal processes and knowledge sharing.

## Tasks
- [x] Describe the problem we solved
- [x] Explain how we solved it - what internal and external services we used, what python libraries etc. 
- [x] Tell about the end result:
  - [x] What has improved? 
  - [x] What is now possible?
  - [x] Add a screenshot of the showcase page with our dataset.
- [x] Explain how DataHub platform with easy visualization helps in understanding stats data

## Acceptance criteria
- [x] We have a blog post that is engaging and informative and offers insight to users who might be looking into automating stats collection for their websites and services
- [x] The blog post elaborates on how to use DataHub as a solution to the problem of stats collection

**Comment by zelima** [comment]
@Branko-Dj can we update this issue with proper description and acceptance criteria. Including progress  Eg on what stage is it now, can we review?

**Comment by Branko-Dj** [comment]
CLOSED.  The blog post is written at https://hackmd.io/T2GXf2bRRm2ldWP5gQj4NA?both

**Comment by akariv** [comment]
(copying from gitter)
The original purpose of the post was to show how we’re using datahub for storing the KPI data and visualising it, in this dataset: https://datahub.io/datahq/datahub-kpis

Therefore the structure of the post should’ve been:
- The problem we want to solve (we’re collecting stats but it’s hard for the team to understand what’s going on and to visualise changes and trends)
- How we solved it (we automated the data collection using a python script and push the results to datahub with custom visualisations)
- How it’s helping (no we enjoy always up-to-date charts of the current status without having to work too hard for it to happen)

That was the gist of the feedback I gave you mid-way, as I had a feeling you were off-track - but I’m afraid the end result is still that way:
- **datahub is only mentioned as context and not as the solution for the problem.**
- There’s an entire section about travis encryption (?).
- You go into detail about the stats we’re collecting and where we’re collecting them from, while I explicitly wrote 'There’s no need to go into details about what are the KPIs or what data we’re collecting’.

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/blog/automated-kpis-collection-and-visualization-of-the-funnels
