### ISSUE TITLE
Travis build passes but no data added to spreadsheet

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/datahub-metrics#11]
## Acceptance criteria:
- [x] Data is being added to spreadsheet
- [ ] If there is a mismatch again, the script should raise an error instead of doing a clean exit

## Tasks: 
- [x] Figure out the cause of the problem of travis build not crashing but no data being added
- [ ] Modify the script to raise an error instead of just exiting

**Comment by Branko-Dj** [comment]
The problem is that in the script, if the field names are not matching those in the spreadsheet, the execution ends without throwing an error which caused confusion

**Comment by zelima** [comment]
@Branko-Dj how it was working if that is the case? Field names were updated?

**Comment by Branko-Dj** [comment]
@zelima I foolishly didn't code it to raise an error when the field names don't match. Instead, I have it do sys.exit(). I will modify the script to raise an error

**Comment by Branko-Dj** [comment]
FIXED! The script is now updated and we will be notified if there is a mismatch again.
