### ISSUE TITLE
Automate collecting the biweekly stats via KPI system

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/datahub-metrics#3]
I want to automate daily stats collection for datahub. There are three google sheets that need filling - daily stats, weekly stats and bi-weekly stats.

## Acceptance criteria
- [x] Able to run a script from a local machine to populate google spreadsheets
- [x] Able to automate the collection via Travis

## Tasks
- [x] Create psqlStats.py script that would collect stats from postgre sql database
- [x] Create pushRequestStats.py script that would collect stats from API requests
- [x] Create pushingTimeStats.py script that would push sample csv files to the datahub and measure time needed to complete the processing on datahub
- [x] Create main.py script that would coordinate these scripts authenticate with google drive and write obtained results into the sheets.
- [x] Automate on the local machine
- [x] Automate on Travis

## Analysis
 - Use gspread and oauth2client to authenticate and write to google sheets
 - Use psycopg2 for authenticating with postgre sql database

**Comment by Branko-Dj** [comment]
FIXED. The stats collection process is now fully automated both locally and from Travis.

**Comment by zelima** [comment]
@Branko-Dj but build is failing on Travis 

```
The command "openssl aes-256-cbc -K $encrypted_5d33e3994bfd_key -iv $encrypted_5d33e3994bfd_iv -in secrets.tar.enc -out secrets.tar -d" failed and exited with 1 during .
```
