### ISSUE TITLE
I need to be able to automate pushing and measuring data processing time on datahub 

### ISSUE THREAD

**Issue by Branko-Dj** [datahq/datahub-metrics#6]
Need to figure out a way to push data from a python script and then measure the time of data processing on the website

## Acceptance criteria
- [ ] Pushing and measuring the time of processing is done on a local machine 
- [ ] Pushing and measuring the time of processing is done on Travis

## Tasks
- [ ] Find a way to have python script interact with the terminal where data-cli is being run and determine the time when the dataset is uploaded
- [ ] Find a way to have python determine when the website has finished processing data.

## Analysis
- Interacting with the terminal will probably be possible with pexpect module, but failing that, it ma be necessary to run data-cli first and then using a python script to determine the time of processing
- @zelima @anuveyatsu suggest sending requests every 1-2 seconds until the processing is completed but this seems a bit inefficient as it may require up to 90 requests in a period of minute and a half. I will keep it in mind while I search for a solution

**Comment by zelima** [comment]
@Branko-Dj how about writing small python script: We can stat measuring time before `data push X` -->  once it's done  --> it's on website Eg

```
import time
import subprocess
import requests

push_start = time.start()
url = subprocess.check_output([data, push, my_dataset], stderr=subprocess.STDOUT)
push_end = time.stop()
process_start = time.start()
while True:
    response = requests.get(url)
    if response.statsus == 200:
        break
    time.sleep(1)
process_end = time.stop()

# do calculation 
```

**Comment by Branko-Dj** [comment]
@zelima I need to push and measure the time of processing on the website. I think that what you wrote is measuring how much time the data-cli will take to upload it. But I need the time measured from the moment that data-cli finishes it's upload until the moment the webpage shows tables. 

The problem I'm stuck on is how to have the script interact with terminal to push a file and then get from terminal the name of the link where the dataset is.

**Comment by zelima** [comment]
@Branko-Dj the second part is measuring time after upload till the table is displayed, no?

* Data CLI will return you the URL once it's done (so you know what page you need to search on datahub)
* Until it's published you will get 404, right (as it's not there yet)? 
  * meaning you can request until you get 200 
  * or alternatively there's a message on revision page `your data is processing` os something like that --> you can send the requests every second until that message is gone
     * once it's gone --> data is processed --> record time

**Comment by anuveyatsu** [comment]
@Branko-Dj @zelima here is my thoughts:

1. push a dataset using python script or using CLI directly (doing it via Travis is trivial)
2. right after the dataset is pushed, you can run a Python script that will check revision status. It is possible since Travis executes commands synchronously.
    * to check the status of revision use API, e.g., do get request every 1-2 seconds for https://api.datahub.io/source/core/finance-vix/50
    * you need to track time of first get request and the time of the last one (when status is either SUCCEEDED or FAILED)

**Comment by zelima** [comment]
@anuveyatsu :+1:  even better

**Comment by Branko-Dj** [comment]
@zelima @anuveyatsu Thank you for your help and suggestions. I will have to think about measuring time processing some more and fall back on sending requests every 1-2 seconds if I don't find a more effective solution.

**Comment by Branko-Dj** [comment]
FIXED. By using pexpect the script is able to communicate with terminal and push a dataset and by sending requests to the page, in short time intervals the script is able to determine the time when the dataset is processed.

**Comment by zelima** [comment]
@Branko-Dj could you please refer to the commit that fixes this?

**Comment by Branko-Dj** [comment]
The scripts will be uploaded to https://github.com/datahq/datahub-metrics as soon as I can familiarize myself with encrypting sensitive information via travis
